### ISSUE TITLE
Branch protection for master

### ISSUE THREAD

**Issue by hisener** [hisener/bbm487s2017g1#3]
We will start the implementation of the application with this iteration. I think we should change this setting:

https://github.com/hisener/bbm487s2017g1/settings/branches

- [x] Protect master branch
Disables force-pushes to this branch and prevents it from being deleted.
    - [x] Require pull request reviews before merging
    When enabled, all commits must be made to a non-protected branch and submitted via a pull request with at least one approved review and no changes requested before it can be merged into master.
    - [x] Require status checks to pass before merging
    Choose which status checks must pass before branches can be merged into master. When enabled, commits must first be pushed to another branch, then merged or pushed directly to master after status checks have passed.
    - [x] Include administrators
    Enforce all configured restrictions for administrators.

More information: https://help.github.com/articles/defining-the-mergeability-of-pull-requests/

What do you think? @ahmed-samil @naciyeguzel

**Comment by ahmed-samil** [comment]
Working on different branches is good but when we commit deliverable documents, we might need to commit them directly because of submit deadline.

**Comment by hisener** [comment]
@ahmed-samil Actually, we will not work on different branches. We will use them for peer review and Travis will run a build for pull requests. We will make sure everything is ok and then, they will be merged and added to the master branch. Please take a look PR #1 and #2.
