### ISSUE TITLE
Self Checkout should updated for books that is in waiting list 

### ISSUE THREAD

**Issue by naciyeguzel** [hisener/bbm487s2017g1#41]

**Comment by hisener** [comment]
Checkout or return?  Or I didn't understand? What do you mean?

**Comment by naciyeguzel** [comment]
Yes it should be return. When x user returns the book, y user should get the book that is in wait list of y user or the system should ask to y user whether y wants to get the book

**Comment by ahmed-samil** [comment]
When a user checks out a book it is added to user if there is nobody in the book's waitlist. If there exists at least one user on the waitlist, then s/he (the user who tries to check out the book) is added to at the end of waitlist.
