### ISSUE TITLE
Notification on waitlist

### ISSUE THREAD

**Issue by ahmed-samil** [hisener/bbm487s2017g1#46]
How should we notify user on the waitlist, when book becomes available?

**Comment by hisener** [comment]
Using `Notifitactions` button -> `Notifications (1)`, maybe?

**Comment by ahmed-samil** [comment]
Yes, but how will we implement notifications?
We can make something like this:

1. User logs in then system checks waitlist.
2. For every book in waitlist, get first added record.
3. Check if book is available. Continue with next book if book is not available
4. From step 2, check if first records belong to this user.
5. If any of the first records belong to user, create a notification (Book X is available, would you like to loan it?)
6. If user approves notification, add book to user then delete record from waitlist.
7. Else delete record from waitlist.

**Comment by ahmed-samil** [comment]
Nope. Waitlist is about giving notifications.
